name: Python application (3cases) DOCKER build

on:
  push:
    branches: [python-ci-workflow]
  pull_request:
    branches: [python-ci-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Build & Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: sk37025/github-action-project
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
